### PR TITLE
router setup and folder structure done

### PR DESCRIPTION
**Pull request by ShravaniAK**

### CODE REVIEW

**Review by DhruvDave12 — CHANGES_REQUESTED** [review]
Why did u delete package-lock ?

**Comment by DhruvDave12** [comment]
To fix that delete the node_modules and existing package-lock in local if any and then do "npm i" and then push with the new package-lock. This current version might cause problems to other

**Comment by ShravaniAK** [comment]
ok sir will do that

**Review by kalashshah — APPROVED** [review]
LGTM!

**Comment by DhruvDave12** [comment]
LGTM!!

**Review by DhruvDave12 — APPROVED** [review]

**Pull request merged**
